# iOS CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"

    steps:
      - checkout

      - run:
          name: Set timezone and check current datetime
          command: |
            sudo systemsetup -settimezone Europe/Warsaw
            echo "Today is $(date +"%Y-%m-%d %T")"

#      - restore_cache:
#          name: Restore Yarn Package Cache
#          keys:
#            - dependency-cache-{{ checksum "yarn.lock" }}
#            - dependency-cache-

      - run:
          name: Install project
          # there is an issue with yarn and cache during executed on CI; for now we just run it twice, second should
          # be successful. Check it later if updates fixed the issue
          command: |
            yarn || true
            yarn || true

#      - save_cache:
#          name: Save Yarn Package Cache
#          key: dependency-cache-{{ checksum "yarn.lock" }}
#          paths:
#            - ./node_modules

      - run:
          name: Building WebUI for distribution
          command: |
            yarn buildforelectron

      - run:
          name: Building gns3server
          command: |
            python -V
            pip install -r scripts/requirements.txt
            python scripts/build.py download
            python scripts/build.py build_exe -b dist/exe.gns3server -s
            python scripts/build.py validate -b dist

      - run:
          name: Dist project
          command: |
            yarn electron-builder --mac --x64

      - run:
          name: Gather artifacts
          command: |
            mkdir artifacts
            cp build/*.dmg artifacts/

      - store_artifacts:
          path: artifacts
          destination: artifacts

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v.*/

